//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by RmtSensing.rc
//
#define IDD_ABOUTBOX                    100
#define IDR_MAINFRAME                   128
#define IDR_RMTSENTYPE                  129
#define IDR_RMTSENSINGTOOLBAR           130
#define IDR_PICTUREHISTOGRAMME          131
#define IDD_PICTUREHISTOGRAME_DLG       132
#define IDR_CUMULATIFHISTOGRAMME        132
#define IDD_SPLASHSCREEN                139
#define IDB_TFESPLASH                   141
#define IDB_PICTUREHISTOGRAMME_DLG      142
#define IDB_OPTIMISATION_RADIO          143
#define IDD_LINEAR_CONTRAST_ENHANCEMENT 144
#define IDD_LOGARITHMIC_EXPANSION       145
#define IDD_EXPONENTIAL_EXPANSION       147
#define IDD_PIECE_WISE_OPTIMISATION     148
#define IDD_OPTIMISATIONS_DLG           148
#define IDD_PICTURE_HISTOGRAMME         150
#define IDI_RGB                         151
#define IDI_OUTILS_HISTOGRAMMEDELIMAGE  152
#define ID_PICHIST_SETTINGS_BLUE        1001
#define ID_PICHIST_SETTINGS_GREEN       1002
#define ID_PICHIST_SETTINGS_GRAPH_TTL_STATE 1003
#define ID_PICHIST_SETTINGS_GRAPH_XTTL_STATE 1004
#define ID_PICHIST_SETTINGS_GRAPH_YTTL_STATE 1005
#define ID_PICHIST_SETTINGS_GRAPH_TTL   1006
#define ID_PICHIST_SETTINGS_GRAPH_XTTL  1007
#define ID_PICHIST_SETTINGS_GRAPH_YTTL  1008
#define ID_PICHIST_SETTINGS_PERCENTAGE_SCLY 1009
#define ID_PICHIST_SETTINGS_SCLX        1010
#define ID_PICHIST_SETTINGS_SCLY        1011
#define ID_PICHIST_SETTINGS_MAXY_RGB    1012
#define ID_PICHIST_SETTINGS_MAXY_USER_PERCENT_RADIO 1013
#define ID_PICHIST_SETTINGS_GRAPH_TYPE_COURBE 1014
#define ID_PICHIST_SETTINGS_MAXY_USER_PIXEL_RADIO 1015
#define ID_PICHIST_SETTINGS_MAXY_USER_PERCENT 1016
#define ID_PICHIST_SETTINGS_MAXY_USER_PIXELS 1017
#define ID_PICHIST_SETTINGS_GRAPH_TYPE_POINTS 1018
#define ID_PICHIST_SETTINGS_GRAPH_TYPE_DISCRET 1019
#define ID_PICHIST_SETTINGS_XQUADRILLAGE 1021
#define ID_PICHIST_SETTINGS_YQUADRILLAGE 1022
#define ID_PICHIST_SETTINGS_RED         1023
#define IDC_RADIO_MAXY_DIVN             1024
#define IDC_MAXY_DIV_N                  1025
#define IDC_RADIO_MAXY_PERCENT_USER     1026
#define IDC_MAXY_PERCENT_USER           1027
#define IDC_RADIO_MAXY_PIXELS_USER      1028
#define IDC_MAXY_PIXELS_USER            1029
#define IDC_RADIO_MAXX_DIVN             1030
#define IDC_BMIN_SLIDER                 1030
#define IDC_MAXX_DIV_N                  1031
#define IDC_BMAX_SLIDER                 1031
#define IDC_RADIO_MAXX_PERCENT_USER     1032
#define IDC_BMIN_EDIT                   1032
#define IDC_MAXX_PERCENT_USER           1033
#define IDC_BMAX_EDIT                   1033
#define IDC_X_COORDS                    1033
#define IDC_RADIO_MAXX_PIXELS_USER      1034
#define IDC_Y_COORDS                    1034
#define IDC_MAXX_PIXELS_USER            1035
#define IDC_X_COORDS1                   1035
#define IDC_PROPERTY_SHEET              1035
#define IDC_Y_COORDS1                   1036
#define IDC_MAX_POINTS                  1036
#define IDC_X_COORDS2                   1037
#define IDC_Y_COORDS2                   1038
#define IDC_CURRENT_POINT               1038
#define IDC_R_EQUAL_V_B                 1039
#define ID_PICTURE_INFO                 32772
#define ID_OUTILS_HISTOGRAMMEDELIMAGE   32774
#define ID_OUTILS_PARAMTRES             32781
#define ID_OUTILS_COMPOSANTEROUGE       32782
#define ID_OUTILS_COMPOSANTEVERTE       32783
#define ID_OUTILS_COMPOSANTEBLEU        32784
#define ID_OUTILS_QUADRILLAGEX          32787
#define ID_OUTILS_QUADRILLAGEY          32788
#define ID_OUTILS_COURBE                32790
#define ID_OUTILS_DISCRET               32791
#define ID_OUTILS_POINTS                32792
#define ID_OUTILS_ECHELLEYENPOURCENT    32796
#define ID_OUTILS_ECHELLEY              32797
#define ID_OUTILS_ECHELLEX              32798
#define ID_OUTILS_TITREAXEDESX          32802
#define ID_OUTILS_TITREAXEDESY          32803
#define ID_OUTILS_TITREDUGRAPHE         32804
#define ID_OUTILS_HISTOGRAMMEUMULATIF   32810
#define ID_OUTILS_EXPANSIONLINAIRE      32816
#define ID_OUTILS_CENTR                 32824
#define ID_OUTILS_CENTRE                32825
#define ID_OUTILS_AJUSTXY               32826
#define ID_OUTILS_AJUSTEXY              32827
#define ID_OUTILS_EXPANSIONLINAIREAVECSATURATION 32834
#define ID_OUTILS_COMPOSANTESRGB        32836
#define ID_OUTILS_EXPANSIONLOGARITHMIQUE 32839
#define ID_OUTILS_EXPANSIONEXPONENTIELLE 32840
#define ID_OUTILS_EXPANSIONLINAIRESEGMENTE 32843
#define ID_TEXT                         59142

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        153
#define _APS_NEXT_COMMAND_VALUE         32844
#define _APS_NEXT_CONTROL_VALUE         1040
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
